export const CHANGE_BLUR_FILTER = "CHANGE_BLUR_FILTER";
export const CHANGE_HUE_ROTATE_FILTER = "CHANGE_HUE_ROTATE_FILTER";
export const CHANGE_INVERT_FILTER = "CHANGE_INVERT_FILTER";
export const CHANGE_GRAY_SCALE_FILTER = "CHANGE_GRAY_SCALE_FILTER";
export const CHANGE_SEPIA_FILTER = "CHANGE_SEPIA_FILTER";
export const CHANGE_SATURATION_FILTER = "CHANGE_SATURATION_FILTER";
export const CHANGE_BRIGHTNESS_FILTER = "CHANGE_BRIGHTNESS_FILTER";
export const CHANGE_CONTRAST_FILTER = "CHANGE_CONTRAST_FILTER";
export const CHANGE_NONE_FILTER = "CHANGE_NONE_FILTER";
export const CHANGE_SOLID_BACKGROUND_FILTER = "CHANGE_SOLID_BACKGROUND_FILTER";
export const CHANGE_LINEAR_GRADIENT_FILTER = "CHANGE_LINEAR_GRADIENT_FILTER";
export const CHANGE_RADIAL_GRADIENT_FILTER = "CHANGE_RADIAL_GRADIENT_FILTER";
export const CHANGE_TYPE_CHOSEN_FILTER = "CHANGE_TYPE_CHOSEN_FILTER";
export const CHANGE_CLEAR_ALL_FILTER = "CHANGE_CLEAR_ALL_FILTER";

export const CHANGE_BACKGROUND1_COLOR = "CHANGE_BACKGROUND1_COLOR";
export const CHANGE_BACKGROUND2_COLOR = "CHANGE_BACKGROUND2_COLOR";

export const CHANGE_INCREMENT1_COLOR  = "CHANGE_INCREMENT1_COLOR";
export const CHANGE_INCREMENT2_COLOR  = "CHANGE_INCREMENT2_COLOR";
export const CHANGE_MIX_BLEND_MODE   = "CHANGE_MIX_BLEND_MODE";
export const CHANGE_GRADIENT_DIRECTION   = "CHANGE_GRADIENT_DIRECTION";
export const CHANGE_GRADIENT_POSITION   = "CHANGE_GRADIENT_POSITION";
export const CHANGE_GRADIENT_SIZE   = "CHANGE_GRADIENT_SIZE";
export const CHANGE_OPACITY_VALUE = "CHANGE_OPACITY_VALUE";